### ISSUE TITLE
StackOverflowError on campaign load

### ISSUE THREAD

**Issue by JamzTheMan** [JamzTheMan/MapTool#10]
Opening BoT campaign with jvm default stack size caused fatal error...

https://sentry.io/nerps/nerps-maptool/issues/338315719/

```
StackOverflowError: None
    at java.util.regex.Pattern$CharProperty$1.isSatisfiedBy(Pattern.java:3771)
    at java.util.regex.Pattern$7.isSatisfiedBy(Pattern.java:5271)
    at java.util.regex.Pattern$CharProperty.match(Pattern.java:3776)
    at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
...
(1019 additional frame(s) were not displayed)
```

**Comment by JamzTheMan** [comment]
Unable to duplicate now.
