### ISSUE TITLE
java.lang.NullPointerException from MacroButtonDialog on MacOS

### ISSUE THREAD

**Issue by klannon** [JamzTheMan/MapTool#111]
**Describe the bug**
There is a NPE generated by opening the Macro editing dialog on MacOS.  The NPE appears to be triggered during the rendering of the UI elements, in particular, the `JMenuBar` attached to the dialog.  Doing some research, I think this is because MapTools is using the MacOS menubar at the the top of the screen (i.e. ```System.setProperty("apple.laf.useScreenMenuBar", "true");```) which is inconsistent with putting a menubar in a window.  If I comment [that line](https://github.com/JamzTheMan/MapTool/blob/master/src/main/java/net/rptools/maptool/client/MapTool.java#L1539) out, the NPE goes away (but of course, the main menubar is now on the application window instead of at the top of the screen).  I played around a bit trying to get the code to work with the MacOS menu bar at the top of the screen for the main menu, but I couldn't find a way to make it work with the time I have available.  It looks like on possibility that might work would be to switch from a `JMenuBar` to a `JToolBar` since I don't think those conflict with the system menu bar and from some reading I did, they can have non-button elements.  I didn't try it though to see how it would look.  Another alternative might be to just wait until you finish the transition to JavaFX.  It looks like in JavaFX, you choose a specific menu bar to become the system one via ```menuBar.setUseSystemMenuBar(true);``` which seems to operate on specific menu bars.  That's a guess though.  I didn't try it out.

**To Reproduce**
1. Open MapTools.
2. Drag a token onto the map.
3. In the "Selection" window, right click to "Add New Macro".
4. Right click on the "(new)" macro and select "Edit..."
5.  The NPE occurs during the dialog rendering.

**Expected behavior**
No NPE when opening the macro editing dialog.  😄 

**MapTool Info**
- Version: 1.5.4.3
- Install: New

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Version 10.14.1

**Additional context**
Stack trace:
```
java.lang.NullPointerException
	at java.desktop/com.apple.laf.AquaMenuPainter.paintMenuBarBackground(AquaMenuPainter.java:149)
	at java.desktop/com.apple.laf.AquaMenuBarUI.paint(AquaMenuBarUI.java:82)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:797)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5262)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1633)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1608)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1546)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1313)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1060)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:78)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:115)
	at java.desktop/java.awt.Container.paint(Container.java:2000)
	at java.desktop/java.awt.Window.paint(Window.java:3940)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:868)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:840)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:840)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:815)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:764)
	at java.desktop/javax.swing.RepaintManager.access$1200(RepaintManager.java:69)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1880)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:38)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Debug Info:
```
==== MapTool Information ====
MapTool Version: 1.4.5.3
MapTool Home...: /Users/klannon/.maptool-Nerps
Max mem avail..: 4,096M
Max mem used...: 268,435,456M
Custom Property: -DMAPTOOL_DATADIR=.maptool-Nerps

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: /Applications/RPTools/MapTool NERPS.app/Contents/PlugIns/Java.runtime/Contents/Home
Java Version: 10.0.2
Result of executing 'java -version':
............: Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
............: Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)


==== OS Information ====
OS Name........: Mac OS X
OS Version.....: 10.14.1
OS Architecture: x86_64
PATH...........: /usr/bin:/bin:/usr/sbin:/sbin
Number of Procs: 8

==== User Information ====
User Name: klannon
User Home: /Users/klannon
User Dir.: /Applications/RPTools/MapTool NERPS.app/Contents/Java

==== Network Interfaces ====
Display Name..: en9
Interface Name: en9
Address...: fe80:0:0:0:aede:48ff:fe00:1122%en9

Display Name..: utun0
Interface Name: utun0
Address...: fe80:0:0:0:8cd0:38b5:5c94:7155%utun0

Display Name..: awdl0
Interface Name: awdl0
Address...: fe80:0:0:0:a8c1:f0ff:fec1:511f%awdl0

Display Name..: en0
Interface Name: en0
Address...: 192.168.1.77

Display Name..: lo0
Interface Name: lo0
Address...: fe80:0:0:0:0:0:0:1%lo0
Address...: 0:0:0:0:0:0:0:1%lo0
Address...: 127.0.0.1

Host Address...: 192.168.1.77
Default Gateway: 192.168.1.254

==== Locale Information ====
Country.: United States
Language: English
Locale..: English (United States)
Variant.: 

==== Display Information ====
Number of Displays: 1
Display 1: 1680x1050(32)

==== Internet Gateway Devices ====
	Error scanning for IGDs.
	No IGDs Found!
```

**Comment by JamzTheMan** [comment]
Thanks for the report. FYI I'm deep into a rewrite and given the difficulty I have replicated Mac issues without a mac, I'll probably defer this to MapTool 2.0 as this is a UI issue and I'm rewriting the whole UI.
