### ISSUE TITLE
java.lang.NullPointerException when opening campaign file

### ISSUE THREAD

**Issue by jcc10** [JamzTheMan/MapTool#119]
The error is as follows:

```
java.lang.NullPointerException
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:351)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderTokens(ZoneRenderer.java:3337)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderZone(ZoneRenderer.java:1229)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.paintComponent(ZoneRenderer.java:790)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1313)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:857)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:840)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:840)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:815)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:764)
	at java.desktop/javax.swing.RepaintManager.access$1200(RepaintManager.java:69)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1880)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:38)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

Right now I am more concerned with recovering the file, if someone could tell me what to delete from the file, I would be really grateful.

**Comment by jcc10** [comment]
[Borked file.zip](https://github.com/JamzTheMan/MapTool/files/2725579/Borked.file.zip)

This is a zip of the file, I just need to completely remove the campsite map, I have no idea how to gracefully remove it.

**Comment by Phergus** [comment]
Campsite map removed.  Rename to "Session 1-Start Fixed.cmpgn" after download.


[Session 1-Start Fixed.zip](https://github.com/JamzTheMan/MapTool/files/2725624/Session.1-Start.Fixed.zip)

**Comment by JamzTheMan** [comment]
Thanks @Phergus.

Do we know what the root cause was? Was it a corrupt image file?

**Comment by Phergus** [comment]
Naw.  I didn't bother looking.  Just deleted the problem map.

**Comment by jcc10** [comment]
It started when I added a previously saved character token. Saved from the same session might I add.

I'll see if I can re-create the issue with a cleaner setup.

**Comment by jcc10** [comment]
Ok, Import this: 

[Borked character.zip](https://github.com/JamzTheMan/MapTool/files/2798575/Borked.character.zip)

Into any campaign and it should crash. So at least now it's repeatable!
