### ISSUE TITLE
IllegalArgumentException: Width (0) and height (1) cannot be <= 0

### ISSUE THREAD

**Issue by JamzTheMan** [JamzTheMan/MapTool#24]
https://sentry.io/nerps/nerps-maptool/issues/400070924/

```
IllegalArgumentException: Width (0) and height (1) cannot be <= 0
    at net.rptools.maptool.client.ui.drawpanel.DrawablesPanel.drawDrawables(DrawablesPanel.java:93)
    at net.rptools.maptool.client.ui.drawpanel.DrawablesPanel.paintComponent(DrawablesPanel.java:85)
    at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:38)
...
(33 additional frame(s) were not displayed)

Width (0) and height (1) cannot be <= 0
```

**Comment by JamzTheMan** [comment]
From user:
> my preview windows was small I guess - it wasn't even on the screen and I had to scroll down to see it. So I expanded the window some and it seems OK now.
