### ISSUE TITLE
Error when disconnecting with UPnP

### ISSUE THREAD

**Issue by JamzTheMan** [JamzTheMan/MapTool#48]
Reported via Forums:
http://forums.rptools.net/viewtopic.php?f=60&t=23681&p=268865#p268861

> Regarding UPnP, I don't need to use it! Just a very minor, circumventable annoyance/non-optimal thing. I can just port forward and it's just as well as long as my local IP doesn't change - or I can just put up with having to disconnect twice, which is really not a huge strain. Here's the full error text when disconnecting with UPnP on:

> 1.4.1.8 doesn't have this issue. 1.4.0.5 doesn't seem to work with port forwarding on my particular router at all, but that's a different problem.

> Router: Netgear WNDR3700

*Stacktrace*
```
java.lang.NullPointerException
   at net.rptools.maptool.util.UPnPUtil.closePort(UPnPUtil.java:207)
   at net.rptools.maptool.client.MapTool.disconnect(MapTool.java:1108)
   at net.rptools.maptool.client.MapTool.stopServer(MapTool.java:984)
   at net.rptools.maptool.client.AppActions.disconnectFromServer(AppActions.java:2007)
   at net.rptools.maptool.client.AppActions$57.execute(AppActions.java:1999)
   at net.rptools.maptool.client.AppActions$ClientAction.actionPerformed(AppActions.java:2828)
   at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
   at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
   at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
   at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
   at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
   at de.muntjak.tinylookandfeel.TinyMenuItemUI.doClick(Unknown Source)
   at de.muntjak.tinylookandfeel.TinyMenuItemUI$MouseInputHandler.mouseReleased(Unknown Source)
   at java.awt.Component.processMouseEvent(Component.java:6533)
   at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
   at java.awt.Component.processEvent(Component.java:6298)
   at java.awt.Container.processEvent(Container.java:2237)
   at java.awt.Component.dispatchEventImpl(Component.java:4889)
   at java.awt.Container.dispatchEventImpl(Container.java:2295)
   at java.awt.Component.dispatchEvent(Component.java:4711)
   at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
   at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
   at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
   at java.awt.Container.dispatchEventImpl(Container.java:2281)
   at java.awt.Window.dispatchEventImpl(Window.java:2746)
   at java.awt.Component.dispatchEvent(Component.java:4711)
   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
   at java.awt.EventQueue.access$500(EventQueue.java:97)
   at java.awt.EventQueue$3.run(EventQueue.java:709)
   at java.awt.EventQueue$3.run(EventQueue.java:703)
   at java.security.AccessController.doPrivileged(Native Method)
   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
   at java.awt.EventQueue$4.run(EventQueue.java:731)
   at java.awt.EventQueue$4.run(EventQueue.java:729)
   at java.security.AccessController.doPrivileged(Native Method)
   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
   at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
   at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:38)
   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by JamzTheMan** [comment]
should be fixed upstream in 1.5
