### ISSUE TITLE
1.4.4.2 JAR File not opening on Win10.1 & OS X 10.13.3

### ISSUE THREAD

**Issue by ErikWPotter** [JamzTheMan/MapTool#60]
- The .exe installer installs a functional application on my Win10.1 machine
- The .pkg installer installs a functional application on my OS X 10.13.3 machine
- Both systems are running fully patched latest versions of the 64bit JRE on fully patched 64bit OSes (not that the installed version should be used by the new 1.4.4.x bundles)
- Running the 1.4.4.0 .jar directly on my OS X machine works fine
- Running the 1.4.4.2 .jar directly on my OS X machine does not open and displays the error "The Java JAR file "MapTool-1.4.4.2.rar" could not be launched. Check the Console for possible error messages. I enabled Show Console in the control panel and it never opened when I tried to run the jar. The Console did open for the embedded java on https://www.java.com/verify/. I left the console open and ran the jar again but nothing new appeared in the console.
- Running the 1.4.4.2 .jar directly on my Win10.1 machine does not open and displays the error "Java Virtual Machine Launcher Error: A JNI error has occured, please check your installation and try again"

**Comment by Phergus** [comment]
> Running

 the 1.4.4.2 .jar directly on my Win10.1 machine does not open and displays the error "Java Virtual Machine Launcher Error: A JNI error has occured, please check your installation and try again"
Same here in regards to the last item.

**Comment by Phergus** [comment]
That's because it was built for Java 9.

> Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/rptools/maptool/client/LaunchInstructions has bee
n compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only
 recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

**Comment by JamzTheMan** [comment]
Correct. 1.4.4.2 requires Java 9 now. I doubt I will release multi-release Jars for this project so either you will have to install Java 9+ (haven't tested with Java 10 yet) or use the packaged versions)

**Comment by ErikWPotter** [comment]
My bad. Was mistakenly thinking it still had the JRE built into it...but its only a jar.
Thanks.
